# Generated by Django 5.1.5 on 2025-01-25 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Enter the name of the district', max_length=255)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Enter the name of the region', max_length=255)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='KinderGarten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Max 500 characters', max_length=500)),
                ('longitude', models.FloatField(blank=True, help_text='Longitude of the location', null=True)),
                ('latitude', models.FloatField(blank=True, help_text='Latitude of the location', null=True)),
                ('phone', models.CharField(help_text='Enter the phone number of the kindergarten', max_length=255)),
                ('inn', models.CharField(help_text='Enter the INN of the kindergarten', max_length=255)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kindergartens', to='kindergarten.district')),
            ],
            options={
                'verbose_name': 'Kinder Garden',
                'verbose_name_plural': 'Kinder Gardens',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='kindergarten.region'),
        ),
        migrations.CreateModel(
            name='KinderGartenCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kindergartens', to='core.camera')),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='kindergarten.kindergarten')),
            ],
            options={
                'verbose_name': 'Kinder Garden Camera',
                'verbose_name_plural': 'Kinder Garden Cameras',
                'unique_together': {('kindergarten', 'camera')},
            },
        ),
    ]
