# Generated by Django 5.1.5 on 2025-01-25 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': ('Child',), 'verbose_name_plural': 'Children'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': ('Employee',), 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='representativechild',
            options={'verbose_name': ('Child Representative',), 'verbose_name_plural': 'Children Representatives'},
        ),
        migrations.AlterField(
            model_name='child',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='participants.group'),
        ),
    ]
