# Generated by Django 5.1.5 on 2025-01-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=12, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Phone Token',
                'verbose_name_plural': 'Phone Tokens',
            },
        ),
    ]
